=== RoronoaFilip/xml_project/restaurants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="restaurants">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="region" type="regionType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="regionType">
        <xs:sequence>
            <xs:element name="restaurant" type="restaurantType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="restaurantType">
        <xs:sequence>
            <xs:element name="type" type="xs:string" />
            <xs:element name="rating" type="xs:decimal" />
            <xs:element name="description" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

</xs:schema>

=== RoronoaFilip/xml_project/restaurants.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "restaurants.xsl"?>
<restaurants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="restaurants.xsd">
    <region id="reg1" name="Sofia">
        <restaurant id="res-sof-1" name="Ceazer's Pizza">
            <type>Италиански</type>
            <rating>4.5</rating>
            <description>An Amazing Restaurant</description>
        </restaurant>
        <restaurant id="res-sof-2" name="Ceazer's Pizza">
            <type>Италиански</type>
            <rating>4.5</rating>
            <description>An Amazing Restaurant</description>
        </restaurant>
    </region>
    <region id="reg2" name="Burgas">
        <restaurant id="res-bur-1" name="Ceazer's Pizza">
            <type>Италиански</type>
            <rating>4.5</rating>
            <description>An Amazing Restaurant 2</description>
        </restaurant>
    </region>
</restaurants>
